### Get all users

GET http://localhost:3000/api/v1/users

### Get user by id

GET http://localhost:3000/api/v1/users/:id

### Create user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "rfid": "112233",
  "username": "razz22111",
  "password": "admin123",
  "firstname": "Ernesto",
  "email": "razz.ernesto@attendix.com",
  "lastname": "Razo",
  "department": "College of Information Technology",
  "status": "active",
  "role": "admin"
}

### Update user
PATCH http://localhost:3000/api/v1/users/a6165745-0bf6-4c4e-9c86-1e506b5f5b1f
Content-Type: application/json

{
  "firstname": "123123123"
}

### Delete user
DELETE http://localhost:3000/api/v1/users/a6165745-0bf6-4c4e-9c86-1e506b5f5b1f
